# Generated by Django 4.0.5 on 2022-06-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_remove_applicant_id_remove_application_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryId',
            new_name='CategoryId',
        ),
    ]
